version: '3.1'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "dev_rds"
      MYSQL_USER: "devops"
      MYSQL_PASSWORD: "devopstest"