name: Build AWS Infrastructure with Terraform

on:

  workflow_dispatch: # Allow to run this workflow manually from the Actions tab
    inputs:
      trigger:
        description: "apply OR destroy" # apply to build infra, destroy to destroy it all.
        required: true
        default: apply # will choose the word apply for you when triggering the pipeline manually.
        type: choice
        options:
        - apply
        - destroy

env:
  TRIGGER: '${{ inputs.trigger }}' # "manual workflow"

jobs:
  build-aws-infra:
    runs-on: ubuntu-latest